### ISSUE TITLE
bug:Namespace config store/get bug make check fail while crossing namespaces.

### ISSUE THREAD

**Issue by kevinz** [authorizer-tech/access-controller#36]
### Is your feature request related to a problem? Please describe.
Namespace config store/get bug make check fail while crossing namespaces.

// make charles a member of the auth0/iam team
insert tuple:

{
  "relationTupleDeltas": [
    {
      "action": "ACTION_INSERT",
      "relationTuple": {
        "namespace": "github_team",
        "object": "auth0/iam",
        "relation": "member",
        "subject": {
          "id": "charles@auth0.com"
        }
      }
    }
  ]
}

// make members of auth0/iam team admins of auth0/express-jwt
{
  "relationTupleDeltas": [
    {
      "action": "ACTION_INSERT",
      "relationTuple": {
        "namespace": "github_repo",
        "object": "auth0/express-jwt",
        "relation": "repo_admin",
        "subject": {
          "set": {
            "namespace": "github_team",
            "object": "auth0/iam",
            "relation": "member"
          }
        }
      }
    }
  ]
}

// check("github_repo:auth0/express-jwt", "repo_admin", "charles@auth0.com");
check request:

{
  "namespace": "github_repo",
  "object": "auth0/express-jwt",
  "relation": "repo_admin",
  "subject": {
    "id": "charles@auth0.com"
  }
}

response should be :
{
    "allowed": true
}

but 
{
   "allowed":false
}

#### related code

nsConfigSnapshotTimestampKey should be different per namespace

`
	if !ok {
		snapshot, err := a.chooseNamespaceConfigSnapshot(namespace)
		if err != nil {
			if err == ErrNoLocalNamespacesDefined {
				return false, NamespaceConfigError{
					Message: fmt.Sprintf("'%s' namespace is undefined. If you recently added it, it may take a couple minutes to propagate", namespace),
					Type:    NamespaceDoesntExist,
				}.ToStatus().Err()
			}

			return false, internalErrorStatus
		}

		snapshotTimestamp = snapshot.Timestamp

		ctx = NewContextWithNamespaceConfigTimestamp(ctx, snapshotTimestamp)
	} else {
		snapshotTimestamp = peerNamespaceCfgTs
	}

	cfg, err := a.PeerNamespaceConfigStore.GetNamespaceConfigSnapshot(a.ServerID, snapshotTimestamp)
	if err != nil {
		return false, internalErrorStatus
	}

	if cfg == nil {
		return false, NamespaceConfigError{
			Message: fmt.Sprintf("'%s' namespace is undefined. If you recently added it, it may take a couple minutes to propagate", namespace),
			Type:    NamespaceDoesntExist,
		}.ToStatus().Err()
	}
`

### Describe the solution you'd like
namespace should be considered be a part of key when storing/loading snapshots

`
// NewContextWithNamespaceConfigTimestamp returns a new Context that carries the namespace config timestamp.
func NewContextWithNamespaceConfigTimestamp(ctx context.Context, namespace string, timestamp time.Time) context.Context {
	return context.WithValue(ctx, fmt.Sprintf("%s%d", **namespace**, nsConfigSnapshotTimestampKey), timestamp)
}

// NamespaceConfigTimestampFromContext extracts the snapshot timestamp for a namespace
// configuration from the provided context. If none is present, a boolean false is returned.
func NamespaceConfigTimestampFromContext(ctx context.Context, namespace string) (time.Time, bool) {
	timestamp, ok := ctx.Value(fmt.Sprintf("%s%d", **namespace**, nsConfigSnapshotTimestampKey)).(time.Time)
	return timestamp, ok

	if !ok {
		snapshot, err := a.chooseNamespaceConfigSnapshot(namespace)
		if err != nil {
			if err == ErrNoLocalNamespacesDefined {
				return false, NamespaceConfigError{
					Message: fmt.Sprintf("'%s' namespace is undefined. If you recently added it, it may take a couple minutes to propagate", namespace),
					Type:    NamespaceDoesntExist,
				}.ToStatus().Err()
			}

			return false, internalErrorStatus
		}

		snapshotTimestamp = snapshot.Timestamp

		ctx = NewContextWithNamespaceConfigTimestamp(ctx, **namespace**, snapshotTimestamp)
	} else {
		snapshotTimestamp = peerNamespaceCfgTs
	}

	cfg, err := a.PeerNamespaceConfigStore.GetNamespaceConfigSnapshot(a.ServerID, **namespace**, snapshotTimestamp)
	if err != nil {
		return false, internalErrorStatus
	}

	if cfg == nil {
		return false, NamespaceConfigError{
			Message: fmt.Sprintf("'%s' namespace is undefined. If you recently added it, it may take a couple minutes to propagate", namespace),
			Type:    NamespaceDoesntExist,
		}.ToStatus().Err()
	}
`

**Comment by jon-whit** [comment]
👋 @kevinz . Thanks for reporting the issue. I think I understand the problem.

Just to clarify though - the issue is not that you get `allowed: false` but that you get an error indicating that the `github_team` namespace is undefined. And this occurs because the namespace config snapshot context doesn't distinguish between individual namespace snapshots. Is that correct?

I cannot reproduce the scenario where you get `allowed: false`. If the namespace snapshot wasn't defined because of the context issue, then you'd get an error. Could you provide more detail that I can use to reproduce the issue.

FWIW - I agree with you about needing to distinguish between different snapshot keys per namespace. I definitely need to rework that a bit.

**Comment by jon-whit** [comment]
@kevinz could you confirm if the changes in #37 fix your issue?

I was able to reproduce the issue locally where you get an error (see prior comment), and I made changes to propagate namespace snapshot timestamp context independently per namespace. That fixes the issue.

Good catch, and I hope this fixes it for you 👍

**Comment by jon-whit** [comment]
Fixed in release `v0.1.4`. Marking this as resolved. If you find otherwise, please re-open an issue.
